### ISSUE TITLE
В методах указаны неверные ссылки обращения в api

### ISSUE THREAD

**Issue by Dan41kPlay** [Friendosie/pyKeksik#2]
Скорее всего проблема просто в копипасте. Например, при вызове keksik_api.balance() возвращается список от метода keksik_api.payments.get(). Исправь пожалуйста и выпусти новую версию. Также ждём Callback API!

**Comment by Friendosie** [comment]
Привет, я обязательно пофикшу этот момент, поскольку я пишу код на телефоне (из за неимения ПК) реализация Callback API будет нескоро, спасибо за фидбек

**Comment by Friendosie** [comment]
Починил эту ошибку, немного изменил код, как будет время реализую callback
